version: '2'

services:

  web:
    image: nginx:latest
    volumes:
      - ./www:/usr/share/nginx/html
    links:
      - db
    networks:
      - fortress
    labels:
      - "traefik.frontend.rule=Host:${FORTRESS_HOST}"
      - "traefik.port=80"
      - "traefik.frontend.entryPoints=http"

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=foo
      - MYSQL_DATABASE=foo
      - FORTRESS_HOST=${FORTRESS_HOST}
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - fortress
    labels:
      - "traefik.enable=false"

volumes:
  database: {}

networks:
  fortress:
    external:
      name: fortress_web

